name: graduation_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  carousel_slider: ^5.0.0
  image_picker: ^1.0.4
  chewie: ^1.11.3
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  get: ^4.6.6
  http: ^1.2.2
  intl: ^0.20.2
  introduction_screen: ^3.1.14
  pinput: ^5.0.1
  shared_preferences: ^2.3.3
  video_player: ^2.9.5
  percent_indicator: ^4.2.2 
  flutter_highlight: ^0.7.0
  code_text_field: ^1.1.0
  highlight: ^0.7.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
